//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PARKtoXMLService2Soap")]
    public interface PARKtoXMLService2Soap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebService.ServiceReference1.HelloWorldResponse HelloWorld(WebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebService.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetParktoXMLResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParktoXML", ReplyAction="*")]
        WebService.ServiceReference1.GetParktoXMLResponse GetParktoXML(WebService.ServiceReference1.GetParktoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParktoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.GetParktoXMLResponse> GetParktoXMLAsync(WebService.ServiceReference1.GetParktoXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParktoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParktoXML", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.GetParktoXMLRequestBody Body;
        
        public GetParktoXMLRequest() {
        }
        
        public GetParktoXMLRequest(WebService.ServiceReference1.GetParktoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetParktoXMLRequestBody {
        
        public GetParktoXMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParktoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParktoXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.ServiceReference1.GetParktoXMLResponseBody Body;
        
        public GetParktoXMLResponse() {
        }
        
        public GetParktoXMLResponse(WebService.ServiceReference1.GetParktoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParktoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetParktoXMLResult;
        
        public GetParktoXMLResponseBody() {
        }
        
        public GetParktoXMLResponseBody(string GetParktoXMLResult) {
            this.GetParktoXMLResult = GetParktoXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PARKtoXMLService2SoapChannel : WebService.ServiceReference1.PARKtoXMLService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PARKtoXMLService2SoapClient : System.ServiceModel.ClientBase<WebService.ServiceReference1.PARKtoXMLService2Soap>, WebService.ServiceReference1.PARKtoXMLService2Soap {
        
        public PARKtoXMLService2SoapClient() {
        }
        
        public PARKtoXMLService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PARKtoXMLService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PARKtoXMLService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PARKtoXMLService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.HelloWorldResponse WebService.ServiceReference1.PARKtoXMLService2Soap.HelloWorld(WebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebService.ServiceReference1.HelloWorldRequest inValue = new WebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebService.ServiceReference1.HelloWorldRequestBody();
            WebService.ServiceReference1.HelloWorldResponse retVal = ((WebService.ServiceReference1.PARKtoXMLService2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.HelloWorldResponse> WebService.ServiceReference1.PARKtoXMLService2Soap.HelloWorldAsync(WebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebService.ServiceReference1.HelloWorldRequest inValue = new WebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebService.ServiceReference1.HelloWorldRequestBody();
            return ((WebService.ServiceReference1.PARKtoXMLService2Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.GetParktoXMLResponse WebService.ServiceReference1.PARKtoXMLService2Soap.GetParktoXML(WebService.ServiceReference1.GetParktoXMLRequest request) {
            return base.Channel.GetParktoXML(request);
        }
        
        public string GetParktoXML() {
            WebService.ServiceReference1.GetParktoXMLRequest inValue = new WebService.ServiceReference1.GetParktoXMLRequest();
            inValue.Body = new WebService.ServiceReference1.GetParktoXMLRequestBody();
            WebService.ServiceReference1.GetParktoXMLResponse retVal = ((WebService.ServiceReference1.PARKtoXMLService2Soap)(this)).GetParktoXML(inValue);
            return retVal.Body.GetParktoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.GetParktoXMLResponse> WebService.ServiceReference1.PARKtoXMLService2Soap.GetParktoXMLAsync(WebService.ServiceReference1.GetParktoXMLRequest request) {
            return base.Channel.GetParktoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.GetParktoXMLResponse> GetParktoXMLAsync() {
            WebService.ServiceReference1.GetParktoXMLRequest inValue = new WebService.ServiceReference1.GetParktoXMLRequest();
            inValue.Body = new WebService.ServiceReference1.GetParktoXMLRequestBody();
            return ((WebService.ServiceReference1.PARKtoXMLService2Soap)(this)).GetParktoXMLAsync(inValue);
        }
    }
}
